modLoader="javafml"
loaderVersion="[62,)"
license="MIT"

[[mixins]]
config="keybind-mod.mixins.json"

[[mods]]
modId="keybind"
version="${version}"
displayName="Keybind"
description="Bind keys to server actions. Works with the Keybind server plugin."
displayTest="IGNORE_ALL_VERSION"

[[dependencies.keybind]]
modId="forge"
mandatory=true
versionRange="[62,)"
ordering="NONE"
side="CLIENT"

[[dependencies.keybind]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
